### ISSUE TITLE
Fix backward compatibility of mlcp

### ISSUE THREAD

**Issue by mattsunsjf** [marklogic/marklogic-contentpump#10]
As part of ongoing work of mlcp, some xdmp builtins are used to replace corresponding admin functions. Should make it backward compatible when mlcp is run against previous versions.

**Comment by jxchen-us** [comment]
Also found this:
2016-08-11 16:26:20.707 Notice: xdbc: XDMP-UNDFUN: (err:XPST0017) Undefined function xdmp:group-get-audit-event-type-enabled()
2016-08-11 16:26:20.707 Notice: xdbc: at 7:22 [1.0-ml]

**Comment by jxchen-us** [comment]
I can't really verify that my fix works against a b8 server due to the above error.

**Comment by mattsunsjf** [comment]
@jxchen-us Please try again

**Comment by jxchen-us** [comment]
Matt,

I tried it and import works for me too now.  Are these all the backward compatibility issues we are aware of?

Thanks,
Jane

**Comment by sravanr** [comment]
Verified with latest mlcp build running against 8.0-20160831 build and found no XDMP-UNDFUN errors.

**Comment by mattsunsjf** [comment]
I think you should also assign the `closed` label to this issue so that it will be synced correctly.

**Comment by sravanr** [comment]
I am not sure here.

In bugtrack we only move bugs to ship and at the end of the release Rick moves all the bugs in the latest release to close.

Thanks
Sravan Kottam

**Comment by mattsunsjf** [comment]
I was wrong, forget about it.
