### ISSUE TITLE
Enhancement to allow a Java KeyStore to be passed via the command-line for TLS Client Authentication connections 

### ISSUE THREAD

**Issue by mwarnes** [marklogic/marklogic-contentpump#104]
MLCP 9.0-1 added support for TLS connections by passing the '-ssl' parameter on the command line and later controlling the TLS protocol using the '-ssl_protocol' parameter. However, both of these only allow a TLS Server Authentication connection, in order to make a connection to a MarkLogic server that requires TLS Client Authentication as well as Server Authentication an SSLConfigOptions class needs to be written and the requisite SSL Configuration passed to MLCP using the '-conf' parameter.

[Advanced SSL Configuration](https://docs.marklogic.com/guide/mlcp/install#id_62768)

TLS Client Authentication (2-Way Authentication) is now quite a common requirement rather than an 'Advanced' feature and requiring a user to have the necessary skills to code an SSLConfigOptions class to handle a KeyManager makes it unnecessarily difficult to use for a lot of users.

I've written an enhancement (I will submit a Pull Request shortly) which allows the user to pass an existing Java KeyStore and/or Truststore via the MLCP command-line to make a TLS Client Authentication connection without the need to code an SSLConfigOptions class.

The following additional parameters are added to the mlcp options and can be passed along with the existing "-ssl" option.

**-keystore_path & -keystore_passwd**   Path and Password to a Java KeyStore containing the User Private Key(s) and Certificate(s); if available mlcp will select the first available certificate from the KeyStore that satisfy the TLS Certificate Request from the MarkLogic Server 
**-truststore_path & -truststore_passwd**   Path and Password to a Java TrustStore containing any necessay CA Certificates needed to verify the TLS Server Authentication connection. If no TrustStore is provided the default TrustStore used by the existing "-ssl" parameter is used.

Prior to this enhancement attempts to use the "-ssl" parameter for a connection requiring TLS Client Authentication would fail as below unless an SSLConfigOptions class was coded that built a KeyManager explicitly.

```
MacPro-4505:bin mwarnes$ ./mlcp.sh import -host localhost -port 8022 -username admin -password admin -input_file_path /Users/mwarnes/TempScanFile 
19/07/10 16:38:55 INFO contentpump.LocalJobRunner: Content type is set to MIXED.  The format of the  inserted documents will be determined by the MIME  type specification configured on MarkLogic Server.
19/07/10 16:38:55 INFO contentpump.ContentPump: Job name: local_407851638_1
19/07/10 16:38:55 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 1
..
19/07/10 16:38:56 WARN mapreduce.MarkLogicOutputFormat: Unable to connect to localhost to query destination information
19/07/10 16:38:56 ERROR contentpump.LocalJobRunner: Error checking output specification: 
19/07/10 16:38:56 ERROR contentpump.LocalJobRunner: Unable to query destination information, no usable hostname found
```
Issuing the same command but passing a valid Java KeyStore and password allows the connection to be established using TLS Client Authentication without the need to code an SSLConfigOptions class.

```
MacPro-4505:bin mwarnes$ ./mlcp.sh import -host localhost -port 8022 -username admin -password admin -input_file_path /Users/mwarnes/TempScanFile -ssl -keystore_path /Users/mwarnes/mlcpuser.jks -keystore_passwd password
19/07/10 16:39:02 INFO contentpump.LocalJobRunner: Content type is set to MIXED.  The format of the  inserted documents will be determined by the MIME  type specification configured on MarkLogic Server.
19/07/10 16:39:03 INFO contentpump.ContentPump: Job name: local_1930231929_1
19/07/10 16:39:03 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 1
19/07/10 16:39:04 INFO contentpump.LocalJobRunner:  completed 100%
19/07/10 16:39:04 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.MarkLogicCounter: 
19/07/10 16:39:04 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 1
19/07/10 16:39:04 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 1
19/07/10 16:39:04 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 1
19/07/10 16:39:04 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 0
19/07/10 16:39:04 INFO contentpump.LocalJobRunner: Total execution time: 1 sec
```

The same enhancement also allows mlcp to make a connection to a MarkLogic XDBC AppServer that is configured for Certificate-Based Authentication, in this case, you can simply pass the KeyStore and password without a "-username" or "-password"

```
MacPro-4505:bin mwarnes$ ./mlcp.sh import -host localhost -port 8022 -input_file_path /Users/mwarnes/TempScanFile -ssl -keystore_path /Users/mwarnes/mlcpuser.jks -keystore_passwd password
19/07/10 17:26:44 INFO contentpump.LocalJobRunner: Content type is set to MIXED.  The format of the  inserted documents will be determined by the MIME  type specification configured on MarkLogic Server.
19/07/10 17:26:45 INFO contentpump.ContentPump: Job name: local_1542569340_1
19/07/10 17:26:45 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 1
19/07/10 17:26:46 INFO contentpump.LocalJobRunner:  completed 100%
19/07/10 17:26:46 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.MarkLogicCounter: 
19/07/10 17:26:46 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 1
19/07/10 17:26:46 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 1
19/07/10 17:26:46 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 1
19/07/10 17:26:46 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 0
19/07/10 17:26:46 INFO contentpump.LocalJobRunner: Total execution time: 1 sec
```

AppServer log message log showing connection used from certificate passed during TLS Client Authentication.

```
127.0.0.1 - **mlcpuser** [10/Jul/2019:17:26:45 +0100] "POST /eval HTTP/1.1" 200 377 - "Java/1.8.0_191 MarkLogicXCC/10.0-20190529"
127.0.0.1 - **mlcpuser** [10/Jul/2019:17:26:46 +0100] "POST /eval XDBC/1.0" 200 119 - "Java/1.8.0_191 MarkLogicXCC/10.0-20190529"
127.0.0.1 - **mlcpuser** [10/Jul/2019:17:26:46 +0100] "PUT /insert?uri=%2FUsers%2Fmwarnes%2FTempScanFile%2FTempScanFile.txt&locale=en_GB&tzoffset=3600&txnmode=update XDBC/1.0" 200 0 - "Java/1.8.0_191 MarkLogicXCC/10.0-20190529"
127.0.0.1 - **mlcpuser** [10/Jul/2019:17:26:46 +0100] "POST /eval XDBC/1.0" 200 0 - "Java/1.8.0_191 MarkLogicXCC/10.0-20190529"
```

All tests currently run clean except for the following which asserts on a time limit, but that could simply be because my laptop is very busy and is unlikely to be linked to any changes made

```
Failed tests: 
  TestImportBigData.testBug35949:77

Tests run: 197, Failures: 1, Errors: 0, Skipped: 0

    /**
     * This test measures the performance of FileAndDirectoryInputFormat.getSplits
     * If it takes more than two minutes to execute getSplits, than an exception will throw
     * @throws Exception
     */
```

Regards 
Martin Warnes

Senior Engineer, Support (EMEA)
MarkLogic Corporation
martin.warnes@marklogic.com

**Comment by yunzvanessa** [comment]
Fixed in MLCP 10.0-5 (target release date end of Sept). Thank you very much!
