### ISSUE TITLE
MCLP 9 no usable hostname found

### ISSUE THREAD

**Issue by debashissinha** [marklogic/marklogic-contentpump#107]
Hi @ryanjdew,

As advised by you am opening a new issue related to MLCP here with reference to the issue **https://github.com/marklogic/marklogic-data-hub/issues/2832**

With reference to the above queries please find my answers inline

If you could provide the answer to the following questions in a new ticket under the mlcp-contentpump project, it could help speed things along.

Is your cluster behind a VPN and if so, are all members of the cluster reachable from the client running MLCP?

Ans :- No it is not behind a vpn all members can reach it out either  by pingning the tcp ip. By using Database client factory could connect. Even form my own machine. But mlcp is failing.

Are the names for each of the hosts in the cluster valid DNS names that the MLCP client can use to find the hosts?

Ans :- Yes and they are resolving properly .

Is the cluster using SSL/TLS on the app server you're attempting to connect to?
Ans :- Yes 

Solicite  your kind help in this regard.

Also closing the previous issue

Thanks & Regards
Debashis Sinha

**Comment by ryanjdew** [comment]
I believe that the issue may be that you're missing the SSL/TLS options in the MLCP command.

See the following copy options that can be found in the MLCP guide. https://docs.marklogic.com/guide/mlcp/copy#id_81128

-input_ssl boolean 
-input_ssl_protocol string
-output_ssl boolean 
-output_ssl_protocol string

**Comment by debashissinha** [comment]
Hi @ryanjdew 

Many thanks for your input . I can see the version of marklogic server in use is 9 ,so the param **input_ssl_protocol string** in mlcp 10 will it work for my version  which is version 9 .


Can this be set as map in additionalparameter ?
Thanks & Regards
Debashis Sinha

**Comment by debashissinha** [comment]
Also in 10.0.1 release of MLCP i couldnt find the setter method for input_ssl_protocol string

Thanks 
Debashis

**Comment by debashissinha** [comment]
Hi @ryanjdew 

Thanks for your input with only input and output ssl set true i could login . Many thanks for your help.

I am closing the ticket.

Thanking you again.
Debashis
