### ISSUE TITLE
load csvs with empty rows into the database

### ISSUE THREAD

**Issue by babjoi** [marklogic/marklogic-contentpump#111]
a csv file with only header information will not be loaded at all into mlcp.
An option to select if such data would make it easier load without any transform query.

**Comment by jmakeig** [comment]
What is a CSV file with “only header information”? You mean a single line with just column headers and no data? Why would that be useful to load in the first place? Can you tell me more about what you’re trying to accomplish?

**Comment by babjoi** [comment]
It would be needed in a sense that we want to know if the data is loaded
but is empty.
If at any time the data is not loaded that can imply two possibilities:
1. Data was empty or
2. Data was never loaded due to some other unknown issue.

In the later situation, if there were no errors or warnings by the system,
one has to go and cross check why the data was never loaded.
This can be avoided when we load the data into the database irrespective of
its nature.

This is particularly required when there is a batch execution of similar
csvs every day or every week.

**Comment by aroach337** [comment]
Sorry, still not understanding.  If we implemented this option, you would still be unaware of "Data was never loaded due to some other unknown issue."  Wouldn't you still need to investigate?
More importantly, can you give an example of data not being loaded but no error thrown?

**Comment by babjoi** [comment]
I have described what do we do when it is an issue in the statements after the second bullet. 
But that is not the point.
Why can't we have an option to load an empty csv using mlcp which wil load empty element documents?

**Comment by aebadirad** [comment]
MarkLogic is a document database that has globally sharded indexes. Loading 100 documents with 'empty elements' is the same as uploading 1 document with empty elements in it. This isn't RDBMS where each row has a unique PK auto-incremented which create a fundamentally unique mathematical set that you can do counts on.

The URI (esp generated via mlcp) is not a 'field' within the document and does not have any value outside of a pointer to the document within the system and has no intrinsic relationships to other pieces of data in the system (even if you make them 'look' this way, it's just a facade), so leaving a 'shell document' in the system really gains you nothing as searching for empty/null isn't a strength of the (or most document) databases.

What seems more beneficial is if MLCP can return a warning or error every time it encounters a CSV file with no valid rows to turn into documents, so you are aware that MLCP did not attempt to build documents from the file.
