### ISSUE TITLE
copyright year not filled in when building only javadoc

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/marklogic-contentpump#13]
If you build the javadoc standalone using the `javadoc:javadoc` target (as the nightly doc build would like to do), the copyright notice at the bottom of the generated javadoc pages contains the variable `${thisyear}` instead of the actual year. For example, it looks like this:
```
Copyright © ${thisyear} MarkLogic Corporation. All Rights Reserved.
```
It should be possible to build just the javadoc, without giving the lawyers hysterics. :)

You can find the generated javadoc in mapreduce/target/site/javadoc, and you can examine the copyright notice by looking at the very bottom of any pages, such as index.html.

I tried the following two build commands, both with the same result:
```
cd marklogic-contentpump
mvn --projects mapreduce javadoc:javadoc

cd mapreduce
mvn javadoc:javadoc
```
(javadoc:javadoc is the standard maven javadoc target, not some strange thing I invented.)

**Comment by mattsunsjf** [comment]
Please try again @kcoleman-marklogic .

**Comment by kcoleman-marklogic** [comment]
I confirmed that this now works properly. Thanks!
