### ISSUE TITLE
MLCP does not handle quoted fields for non-default delimiter

### ISSUE THREAD

**Issue by eurochriskelly** [marklogic/marklogic-contentpump#146]
When I import the following record:
```
A~B~~D~"Hello~World"~F
A~B~~D~"Hello World"~F
```

with -delimiter "~", the first line fails (SKIPPED), the second line succeeds

When I import the following record:
```
A,B,,D,"Hello,World",F
A,B,,D,"Hello World",F
```
with no delimiter specified,  both lines succeed.

This is a bug because both of the formats above should behave the same way.

**Comment by jmakeig** [comment]
The latter is mostly well specified as CSV. The former isn’t. Can you pre-process into well formed CSV?

**Comment by eurochriskelly** [comment]
We actually went back to the source and asked them to add the quotes next to the delimiters to ensure proper processing. We have seen mlcp complain when there is a quotation mark next to one delimiter but the not the other so we expected this to work. There are  a lot of sources here and most of them provided the data with a tilda delimiter. I'll also look into pre-processing into well-formed CSV in the meantime.

**Comment by jmakeig** [comment]
Issues with delimiters with regular CSV are likely something we’d want to fix. If you have examples, please send create a new issue here. For non-CSV delimiters or quotes, our recommendation should be to pre-process into CSV. The permutations there are near infinite.

(The [CSV RFC](https://tools.ietf.org/html/rfc4180) mostly paved existing cow paths, so there are many different interpretations of “CSV” in the wild.)
