### ISSUE TITLE
command line options doesn't match documentation

### ISSUE THREAD

**Issue by mfgumban** [marklogic/marklogic-contentpump#174]
Some command line options in [documentation](https://docs.marklogic.com/guide/mlcp/import#id_23879) don't seem to match up with what's in code.  The *keystore/*truststore related options, for example: `-keystore_passwd` in the docs, but actually [-keystore_password](https://github.com/marklogic/marklogic-contentpump/blob/82b80ae563d72bf87ace3a6882c32de0528954b6/src/main/java/com/marklogic/contentpump/ConfigConstants.java#L139).

**Comment by yunzvanessa** [comment]
Hi mfgumban,

This issue will be fixed in 10.0.7 release (scheduled in Jun 2021). Thank you for filing this issue!

Best,
Vanessa
