### ISSUE TITLE
test instructions are not up to date

### ISSUE THREAD

**Issue by AdVanOmmen** [marklogic/marklogic-contentpump#179]
WIth current master (mlcp version 10.0.5.2) the instructions in  https://github.com/marklogic/marklogic-contentpump/wiki/Guideline-to-Run-Tests and https://github.com/marklogic/marklogic-contentpump/blob/master/src/test/README are not fully correct. 

For example the port defaults in the pom.xml  are different from what is stated in the given pages, and so are the database names.

From the pom
    \<testDbPort>5276\</testDbPort>
    \<copyDbPort>6276\</copyDbPort>
    \<testDb>mlcp-unittest-db\</testDb>
    \<copyDb>mlcp-unittest-copy-db\</copyDb>

In /src/test/README these are very different.
And in wiki/Guideline-to-Run-Tests there it is stated a basic admin/admin server is enough and that "MLCP tests will make" all the rest that is needed.

Running mvn test gives

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.marklogic.contentpump.TestReturnCode
com.marklogic.xcc.exceptions.JavaScriptException: XDMP-NOSUCHDB: xdmp.database("mlcp-unittest-db") -- No such database mlcp-unittest-db
 [Session: user=admin, cb={default} [ContentSource: user=admin, cb={none} [provider: address=localhost/127.0.0.1:8000, pool=1/64]]]
 [Client: XCC/10.0-5.2, Server: XDBC/10.0-5.2]
in /eval, on line 9
expr: xdmp.database("mlcp-unittest-db")
in /eval
expr: xdmp.database("mlcp-unittest-db")`

**Comment by yunzvanessa** [comment]
Hi AdVanOmmen,

The issue you reported has been fixed. Please refer to the most up-to-date instructions: https://github.com/marklogic/marklogic-contentpump/wiki/Guideline-to-Run-Tests. Thank you for filling this issue!

Vanessa
