### ISSUE TITLE
mlcp  issue with hadoop-hdfs-2.6.0.jar

### ISSUE THREAD

**Issue by priyap9323** [marklogic/marklogic-contentpump#181]
In Apache Hadoop `3.1.0 to 3.1.1`, `3.0.0-alpha1 to 3.0.3`, `2.9.0 to 2.9.1`, and `2.0.0-alpha to 2.8.4`, the user/group information can be corrupted across storing in fsimage and reading back from fsimage.

**Comment by yunzvanessa** [comment]
Hi priyap9323,

MLCP support for HDFS has been deprecated, so this security vulnerability is not applicable. Per 10.0-7 release (scheduled June 2021), the Apache Hadoop library will be bumped up to 2.7.2.

Thanks,
Vanessa
