### ISSUE TITLE
Add proper mlcp SSL support.

### ISSUE THREAD

**Issue by jxchen-us** [marklogic/marklogic-contentpump#19]
mlcp can leverage the Hadoop Connector SSL support through -conf parameter: 

https://lists.marklogic.com/search/?q=ssl%20mlcp#query:ssl%20mlcp%20from%3A%22Jane%20Chen%22+page:1+mid:ny2iy3t4uz2esxbv+state:results

I recently learned that this was actually used by Aetna, and people at World Bank made a syntax error when trying to copy the model.  So it would be worth testing it.

**Comment by jxchen-us** [comment]
copy -input_username admin -input_password admin -input_host localhost -input_port 5275  -output_username admin -output_password admin -output_host localhost -output_port 5276 -mode local -input_ssl -output_ssl

export -username admin -password admin -host jchen -port 5275 -output_file_path /tmp/dump -output_type archive -ssl

IMPORT -username admin -password admin -host jchen -port 5275 -input_file_path /space/hadoop-0.20.2/conf -ssl

**Comment by sravanr** [comment]
Nightly regression now run mlcp on SSL days also. will add specific test to regression in 9.0-1 timeframe.
