### ISSUE TITLE
Deprecated XCC method ContentSourceFactory.newContentSource used sending password as String instead of char[]

### ISSUE THREAD

**Issue by hansenmc** [marklogic/marklogic-contentpump#192]
There are several places in the com.marklogic.mapreduce.utilities.InternalUtilities class that use the [deprecated XCC ContentSourceFactory.newContentSource() method](https://docs.marklogic.com/javadoc/xcc/com/marklogic/xcc/ContentSourceFactory.html#newContentSource-java.lang.String-int-java.lang.String-java.lang.String-java.lang.String-), which sends the password parameter as a string. 

- https://github.com/marklogic/marklogic-contentpump/blob/81c78f8a023c9097d36ad2ca7f3bc130a06ca854/src/main/java/com/marklogic/mapreduce/utilities/InternalUtilities.java#L136
- https://github.com/marklogic/marklogic-contentpump/blob/467aa048e746c0e2ef84efdf1013a9ee6e2d86c2/src/main/java/com/marklogic/mapreduce/utilities/InternalUtilities.java#L376
- https://github.com/marklogic/marklogic-contentpump/blob/467aa048e746c0e2ef84efdf1013a9ee6e2d86c2/src/main/java/com/marklogic/mapreduce/utilities/InternalUtilities.java#L474

It appears that it should use the method which takes the password as a `char[]` (it would be nice if the XCC deprecation message pointed to the preferred method)

**Comment by abika5** [comment]
Hi,

This issue will be fixed in 10.0.9 release (scheduled in Feb 2022).

Regards,
Abika
