### ISSUE TITLE
JsonGenerator createJsonGenerator is deprecated

### ISSUE THREAD

**Issue by hansenmc** [marklogic/marklogic-contentpump#194]
https://fasterxml.github.io/jackson-core/javadoc/2.2.0/com/fasterxml/jackson/core/JsonFactory.html#createJsonGenerator(java.io.OutputStream)
>Deprecated Since 2.2, use createGenerator(Writer) instead.

https://github.com/marklogic/marklogic-contentpump/blob/81c78f8a023c9097d36ad2ca7f3bc130a06ca854/src/main/java/com/marklogic/contentpump/utilities/JSONDocBuilder.java#L59

**Comment by abika5** [comment]
Hi,

This issue will be fixed in 10.0.9 release (scheduled in Feb 2022).

Regards,
Abika
