### ISSUE TITLE
Broken link to http://developer.marklogic.com/pubs/ in JavaDoc footer

### ISSUE THREAD

**Issue by hansenmc** [marklogic/marklogic-contentpump#205]
The footer of the MLCP JavaDocs have a broken link pointing to http://developer.marklogic.com/pubs/ which returns HTTP 404:
>Copyright © 2021 MarkLogic Corporation
>Complete online documentation for MarkLogic Server, XQuery and related components may be found at [developer.marklogic.com](http://developer.marklogic.com/pubs/)
 
That is generated in the build with the maven-javadoc-plugin configuration:
https://github.com/marklogic/marklogic-contentpump/blob/81c78f8a023c9097d36ad2ca7f3bc130a06ca854/pom.xml#L237

**Comment by abika5** [comment]
Hi,

This issue will be fixed in 10.0.9 release (scheduled in Feb 2021). Thank you for filing this issue!

Regards,
Abika
