### ISSUE TITLE
configure maven-compiler-plugin for Java 8

### ISSUE THREAD

**Issue by hansenmc** [marklogic/marklogic-contentpump#207]
The [SegmentAssignmentPolicy uses Long.remainderUnsigned()](https://github.com/marklogic/marklogic-contentpump/blob/cd859b49ec802dc4311cd1168e55fae960c23aeb/src/main/java/com/marklogic/mapreduce/utilities/SegmentAssignmentPolicy.java#L55)

            return (int) Long.remainderUnsigned(u,size);

That function was [introduced in Java 8](https://docs.oracle.com/javase/8/docs/api/java/lang/Long.html#remainderUnsigned-long-long-)

However, the POM has the [maven-compiler-plugin configured with source and target for Java 7](https://github.com/marklogic/marklogic-contentpump/blob/cd859b49ec802dc4311cd1168e55fae960c23aeb/pom.xml#L114)

    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <compilerArgs>
            <arg>-Xlint</arg>
          </compilerArgs>
          <failOnError>true</failOnError>
          <showDeprecation>true</showDeprecation>
          <debug>${compile.debug.symbols.flag}</debug>
          <fork>true</fork>
          <source>1.7</source>
          <target>1.7</target>
        </configuration>
    </plugin>

The MLCP Documentation says that users need Java 8 or later:
https://docs.marklogic.com/guide/mlcp/install#id_44231 
> Oracle/Sun Java JRE 1.8 or later.

The maven-compiler-plugin should be configured for Java 1.8:
https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html

**Comment by rjrudin** [comment]
@abika5 @yunzvanessa I think this can be closed now that Java 11 is required?

**Comment by abika5** [comment]
@hansenmc @rjrudin , As a part of [DBI-393](https://project.marklogic.com/jira/browse/DBI-393), this has been finished. We have upgraded the source and target to 11.
