### ISSUE TITLE
Misleading command line option description

### ISSUE THREAD

**Issue by sanjuthomas** [marklogic/marklogic-contentpump#25]
type - mlcp.bat import (assuming mlcp is in path)

This will list out all the possible options for import command - 

search for -transform_param <String> and check the description. Description says "Name of the transform function"

it should be "Optional extra data to pass through to a custom transformation function"

**Comment by jxchen-us** [comment]
Good catch.  Thank you Sanju!

**Comment by sravanr** [comment]
I see the following
 -transform_param <String>                 **Parameters of the transform function**
