### ISSUE TITLE
incorrect dependency on javax.xml.soap.Node

### ISSUE THREAD

**Issue by mdubinko** [marklogic/marklogic-contentpump#255]
One test in CustomQuery.java has an incorrect dependency on javax.xml.soap.Node
Should be org.w3c.dom.Node (as seen elsewhere in the code). This affects only a single test. This will cause an issue on Java 11 and up, since JAX-WS has gone from deprecated to fully removed, and this class is not available (aside from being the wrong Node class to use anyway).
I have a fix in hand.

**Comment by yunzvanessa** [comment]
https://github.com/marklogic/marklogic-contentpump/pull/256

**Comment by abika5** [comment]
This dependency has been updated as a part of jena upgrade on 11.1.0
