### ISSUE TITLE
Misleading command line option description

### ISSUE THREAD

**Issue by mattsunsjf** [marklogic/marklogic-contentpump#27]
Clone of #25 on 9.0-ea4 branch

**Comment by sravanr** [comment]
-transform_function <String>              Name of the transform function
 -transform_module <String>                Path to the module containing
                                           the transform function
 -transform_namespace <String>             Namespace of the transform
                                           function
 **-transform_param <String>                 Name of the transform function**


                                           
skottam@skottam-z620$ mlcp-9.0/bin/mlcp.sh  version
ContentPump version: 9.0
Java version: 1.8.0_72
Hadoop version: 2.6.0
Supported MarkLogic versions: 6.0 - 9.0

I dont see your change taking an effect in Head

**Comment by mattsunsjf** [comment]
I can see the right description. Please make sure you are on develop branch and code is up-to-date.

**Comment by sravanr** [comment]
successful inserts are
                                           committed
 -transaction_size <number>                Number of requests in one
                                           transaction (default 10)
 -transform_function <String>              Name of the transform function
 -transform_module <String>                Path to the module containing
                                           the transform function
 -transform_namespace <String>             Namespace of the transform
                                           function
 -transform_param <String>                 Parameters of the transform
                                           function
 -type_filter <String>                     Comma-separated list of
                                           document types
