### ISSUE TITLE
MLCP throws invalid skipped message and does not import text document when it has collection info

### ISSUE THREAD

**Issue by sravanr** [marklogic/marklogic-contentpump#28]
I have back ported the test from 9.0, mlcp-da-test15.xml , I see inconsistent behavior between 9.0 vs 8.0 .

I understand the we dont copy collections,quality,permissions in 8.0 but we do in 9.0, this issue is more about not been able to import text documents when we have collections defined on the text document

For simple steps:

-    mlcp import type  forest 
  - Attach F1 to db
  - load content into database
  - Now detach F1 from db
  - Attach F2 to db
  - Import data using mlcp import and input_type forest from F1  
  - Validate results

documents I loaded:

```
xquery version "1.0-ml";

xdmp:document-load("QA_HOME/mlcp/data/text/text1.txt", <options xmlns="xdmp:document-load"><uri>/Test/mlcp-export-xmlquery-filter/text/1.txt</uri><format>text</format><collections><collection>mlcp-export-xmlquery-filter</collection></collections></options>),

xdmp:document-load("QA_HOME/mlcp/data/text/text2.txt", <options xmlns="xdmp:document-load"><uri>/Test/mlcp-export-xmlquery-filter/text/2.txt</uri><format>text</format><collections><collection>mlcp-export-xmlquery-filter</collection></collections></options>),

xdmp:document-load("QA_HOME/mlcp/data/binary/996.jpg", <options xmlns="xdmp:document-load"><uri>/Test/mlcp-export-xmlquery-filter/binary/1.jpg</uri><format>binary</format><collections><collection>mlcp-export-xmlquery-filter</collection></collections></options>),

xdmp:document-load("QA_HOME/mlcp/data/binary/lemon.gif", <options xmlns="xdmp:document-load"><uri>/Test/mlcp-export-xmlquery-filter/binary/2.gif</uri><format>binary</format><collections><collection>mlcp-export-xmlquery-filter</collection></collections></options>),

xdmp:document-set-property("/Test/mlcp-export-xmlquery-filter/naked/example.xml",<fruit><name>apple</name><color>red</color></fruit>);

xdmp:document-set-collections("/Test/mlcp-export-xmlquery-filter/naked/example.xml", "xmldocs"),
xdmp:document-set-property("/Test/mlcp-export-xmlquery-filter/fruit3.xml",<ex:fruit xmlns:ex="http://marklogic.com/example"><name>apple</name><color>red</color></ex:fruit>);


```

Command that I used in the test

```
QA_HOME/mlcp/runmlcp.sh QA_HOME IMPORT  -input_file_path MLD_HOME/Forests/mlcp-f15a -input_file_type forest -host localhost -port 5275 -username admin -password admin -output_collections A -output_uri_prefix /Test1 -mode local
```

Result I see

```
Skipped record: () from /Test/mlcp-export-xmlquery-filter/naked/example.xml in file:/var/opt/MarkLogic/Forests/mlcp-f15a/00000000/TreeData, reason: fragment or link
Skipped record: () from /Test/mlcp-export-xmlquery-filter/text/2.txt in file:/var/opt/MarkLogic/Forests/mlcp-f15a/00000000/TreeData, reason: fragment or link
```

**Comment by jxchen-us** [comment]
This seems like a build issue.  The QA b8_0 directory contains mlcp, XCC and Hadoop Connectors jars from November 2015.

**Comment by sravanr** [comment]
I still see this happening on my local machine with test mlcp-da-test15.xml, I am not sure what is missing so copied the forest to shared location /project/qa/skottam/mlcp-f15a/

Please try to import the documents from that forests and see if you can reproduce the issue.

**Comment by jxchen-us** [comment]
For /Test/mlcp-export-xmlquery-filter/text/2.txt

ordinal	-3758096384

**Comment by jxchen-us** [comment]
Property fragments:
Position 3: URI=/Test/mlcp-export-xmlquery-filter/naked/example.xml
Position 8: URI=/Test/mlcp-export-xmlquery-filter/fruit3.xml
Position 9: URI=/Test/mlcp-export-xmlquery-filter/naked/example.xml

**Comment by sravanr** [comment]
Verified and updated the key, I see little different expected result so logged a differen issue 36 for it.
