### ISSUE TITLE
mlcp:Missing metadata Warning message in mlcp-8.0 branch 

### ISSUE THREAD

**Issue by sravanr** [marklogic/marklogic-contentpump#30]
I have test mlcp-set-copy-col-perm-qlty-false.xml checked in 8.0-nightly

we see 
Skipped record: () from /Test/mlcp-copy-binquery-filter/binary/1.jpg in file:/tmp/mlcp_export_archive/20160920113220-0700-000004-BINARY.zip, reason: Missing metadataSkipped record: () from /Test/mlcp-copy-binquery-filter/binary/2.gif in file:/tmp/mlcp_export_archive/20160920113220-0700-000009-BINARY.zip, reason: **Missing metadata**

My understanding is we dont have metadata in 8.0-nightly and I am expecting no skipped records here.
 test started failing from 09/18/2016.

```
 /space/b8_0/qa/mlcp/runmlcp.sh /space/b8_0/qa import -copy_collections false -copy_permissions false -copy_properties false -copy_quality false -input_file_path /tmp/mlcp_export_archive -input_file_type archive -output_uri_prefix /Test1/  -options_file /space/b8_0/qa/mlcp/data/804/input_option_files/import_options.txt;

```
stdout:
```
stderr/out from shell cmd: rm: cannot remove \u2018/space/b8_0/qa/mlcp/log/mlcpconsolelog.xml\u2019: No such file or directory
16/09/20 11:32:40 INFO contentpump.LocalJobRunner: Content type: XML
16/09/20 11:32:41 INFO contentpump.FileAndDirectoryInputFormat: Total input paths to process : 10
**16/09/20 11:32:41 WARN contentpump.ImportDocumentMapper: Skipped record: () from /Test/mlcp-copy-binquery-filter/binary/1.jpg in file:/tmp/mlcp_export_archive/20160920113220-0700-000004-BINARY.zip, reason: Missing metadata
16/09/20 11:32:41 WARN contentpump.ImportDocumentMapper: Skipped record: () from /Test/mlcp-copy-binquery-filter/binary/2.gif in file:/tmp/mlcp_export_archive/20160920113220-0700-000009-BINARY.zip, reason: Missing metadata**
16/09/20 11:32:41 INFO contentpump.LocalJobRunner:  completed 100%
16/09/20 11:32:41 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.MarkLogicCounter: 
16/09/20 11:32:41 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 11
16/09/20 11:32:41 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 9
16/09/20 11:32:41 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 9
16/09/20 11:32:41 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 0
16/09/20 11:32:41 INFO contentpump.LocalJobRunner: Total execution time: 0 sec

```

**Comment by jxchen-us** [comment]
Is this seen on trunk too?

**Comment by jxchen-us** [comment]
I need more info on this bug:  from which test step did you get the above error?

**Comment by sravanr** [comment]
I see this in all the import commands, so I am not sure on what else I have to provide here for more details.

**Comment by jxchen-us** [comment]
So you mean all import throws the above error, regardless whether copy is set to true or not?

**Comment by sravanr** [comment]
test explicitly written for setting it to false, I dont see this happening in trunk

**Comment by jxchen-us** [comment]
I don't find test mlcp-set-copy-col-perm-qlty-false.xml on trunk.

**Comment by jxchen-us** [comment]
I ran the test.  It failed with:

stderr/out from shell cmd: rm: cannot remove ‘/space/projects/qa-b8/mlcp/log/mlcpconsolelog.xml’: No such file or directory
cp: failed to access ‘/space/projects/qa-b8/mlcp/marklogic-contentpump/conf/’: Not a directory
chmod: cannot access ‘/space/projects/qa-b8/mlcp/marklogic-contentpump/conf/log4j.properties’: Not a directory
ls: cannot access /space/projects/qa-b8/mlcp/marklogic-contentpump/conf/log4j.properties: Not a directory
/space/projects/qa-b8/mlcp/runmlcp.sh: line 40: /space/projects/qa-b8/mlcp/marklogic-contentpump/bin/mlcp.sh: Not a directory
cat: /space/projects/qa-b8/mlcp/log/mlcpconsolelog.xml: No such file or directory
rm: cannot remove ‘/space/projects/qa-b8/mlcp/log/mlcpconsolelog.xml’: No such file or directory

Please provide the minimal required test steps to reproduce the bug.

**Comment by sravanr** [comment]
Regression test mlcp-set-copy-col-perm-qlty-false.xml is passing in local machine with latest mlcp nightly build.
