### ISSUE TITLE
Support modifying document collections within a transform

### ISSUE THREAD

**Issue by RobertSzkutak** [marklogic/marklogic-contentpump#34]

**Comment by jxchen-us** [comment]
Taking this since I have a similar one for metadata.

**Comment by jxchen-us** [comment]
I believe there’s a workaround approach to do this: you just call xdmp:document-insert in your transform function specifying whatever collection you want, and return empty sequence in your transform function.

**Comment by jxchen-us** [comment]
Sending        Modules/MarkLogic/hadoop.xqy
Transmitting file data .
Committed revision 247828.

Fixed.  For more info, see the bugtrack clone and eventually mlcp documentation.
