### ISSUE TITLE
MLCP is missing to log skipped message for Naked properties when importing from a forest 

### ISSUE THREAD

**Issue by sravanr** [marklogic/marklogic-contentpump#36]
Regression test  mlcp-da-test15.xml has a scenario for reproducing this issue.

1. Load following documents into database

```
 xquery version "1.0-ml";
        xdmp:document-insert("/Test/mlcp-export-xmlquery-filter/fruit1.xml",<ex:fruits xmlns:ex="http://marklogic.com/example"><ex:fruit><ex:name>apple</ex:name><ex:color>red</ex:color></ex:fruit>    <ex:fruit ><ex:name>orange</ex:name><ex:color>orange</ex:color></ex:fruit></ex:fruits>,(xdmp:permission("xa", "read")), "xmldocs");
        xdmp:document-insert("/Test/mlcp-export-xmlquery-filter/fruit2.xml",<ex:fruits xmlns:ex="http://marklogic.com/example"><ex:fruit><ex:name>apple</ex:name><ex:color>red</ex:color></ex:fruit> <ex:fruit><ex:name>grape</ex:name><ex:color>purple</ex:color></ex:fruit> </ex:fruits>,(xdmp:permission("xa", "read")), "xmldocs");
        xdmp:document-insert("/Test/mlcp-export-xmlquery-filter/fruit3.xml",<ex:fruits xmlns:ex="http://marklogic.com/example"><ex:fruit><ex:name>watermellon</ex:name><ex:color>green</ex:color></ex:fruit> <ex:fruit><ex:name>orange</ex:name><ex:color>orange</ex:color></ex:fruit> </ex:fruits>,(xdmp:permission("xa", "read")), "xmldocs");
```
```
 declareUpdate();
        xdmp.documentInsert("/Test/mlcp-export-query-filter/JSONfruit1.json", {"fruits" :[ {"fruit": {"name":"apple","color": "red"}},{"fruit": {"name":"orange","color": "orange"}}]},[xdmp.permission("xa", "read")],"jsondocs"),
        xdmp.documentInsert("/Test/mlcp-export-query-filter/JSONfruit2.json", {"fruits" :[ {"fruit": {"name":"apple","color": "red"}},{"fruit": {"name":"kiwi","color": "green"}}]},[xdmp.permission("xa", "read")],"jsondocs"),
        xdmp.documentInsert("/Test/mlcp-export-query-filter/JSONfruit3.json", {"fruits" :[ {"fruit": {"name":"strawberry","color": "red"}},{"fruit": {"name":"orange","color": "orange"}}]},[xdmp.permission("xa", "read")],"jsondocs");
```
```
 xquery version "1.0-ml";

xdmp:document-load("QA_HOME/mlcp/data/text/text1.txt", <options xmlns="xdmp:document-load"><uri>/Test/mlcp-export-xmlquery-filter/text/1.txt</uri><format>text</format><collections><collection>mlcp-export-xmlquery-filter</collection></collections></options>),

xdmp:document-load("QA_HOME/mlcp/data/text/text2.txt", <options xmlns="xdmp:document-load"><uri>/Test/mlcp-export-xmlquery-filter/text/2.txt</uri><format>text</format><collections><collection>mlcp-export-xmlquery-filter</collection></collections></options>),

xdmp:document-load("QA_HOME/mlcp/data/binary/996.jpg", <options xmlns="xdmp:document-load"><uri>/Test/mlcp-export-xmlquery-filter/binary/1.jpg</uri><format>binary</format><collections><collection>mlcp-export-xmlquery-filter</collection></collections></options>),

xdmp:document-load("QA_HOME/mlcp/data/binary/lemon.gif", <options xmlns="xdmp:document-load"><uri>/Test/mlcp-export-xmlquery-filter/binary/2.gif</uri><format>binary</format><collections><collection>mlcp-export-xmlquery-filter</collection></collections></options>),

xdmp:document-set-property("/Test/mlcp-export-xmlquery-filter/naked/example.xml",<fruit><name>apple</name><color>red</color></fruit>);

xdmp:document-set-collections("/Test/mlcp-export-xmlquery-filter/naked/example.xml", "xmldocs"),
xdmp:document-set-property("/Test/mlcp-export-xmlquery-filter/fruit3.xml",<ex:fruit xmlns:ex="http://marklogic.com/example"><name>apple</name><color>red</color></ex:fruit>);

```

Detach your database forest and attach new forest

Now run below query pointing input file path to detached forest

Command and standard out

running following shell command: 
 rm /space/b8_0/qa/mlcp/log/mlcpconsolelog.xml;
/space/b8_0/qa/mlcp/runmlcp.sh /space/b8_0/qa IMPORT  -input_file_path /var/opt/MarkLogic/Forests/mlcp-f15a -input_file_type forest -host localhost -port 5275 -username admin -password admin -output_collections A -output_uri_prefix /Test1 -mode local
(echo '<root xmlns:log4j="'"test"'" >';cat /space/b8_0/qa/mlcp/log/mlcpconsolelog.xml ;echo '</root>')>/space/b8_0/qa/mlcp/log/temp.xml;
     rm /space/b8_0/qa/mlcp/log/mlcpconsolelog.xml

stderr/out from shell cmd: 16/09/27 14:35:07 INFO contentpump.LocalJobRunner: Content type is set to MIXED.  The format of the  inserted documents will be determined by the MIME  type specification configured on MarkLogic Server.
16/09/27 14:35:07 INFO input.FileInputFormat: Total input paths to process : 5
**16/09/27 14:35:08 WARN contentpump.ImportDocumentMapper: Skipped record: () from /Test/mlcp-export-xmlquery-filter/fruit3.xml in file:/var/opt/MarkLogic/Forests/mlcp-f15a/00000000/TreeData, reason: fragment or link**
16/09/27 14:35:08 INFO contentpump.LocalJobRunner:  completed 100%
16/09/27 14:35:08 INFO contentpump.LocalJobRunner: com.marklogic.mapreduce.MarkLogicCounter: 
16/09/27 14:35:08 INFO contentpump.LocalJobRunner: INPUT_RECORDS: 11
16/09/27 14:35:08 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS: 10
16/09/27 14:35:08 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_COMMITTED: 10
16/09/27 14:35:08 INFO contentpump.LocalJobRunner: OUTPUT_RECORDS_FAILED: 0
16/09/27 14:35:08 INFO contentpump.LocalJobRunner: Total execution time: 0 sec

Actual:

I am missing to see skipped message for naked properties and not seeing in the database after import.

16/09/27 14:31:08 WARN contentpump.ImportDocumentMapper: Skipped record: () from _**/Test/mlcp-export-xmlquery-filter/naked/example.xm**_l in file:/project/qa/skottam/Forests/mlcp-f15a/00000002/TreeData, reason: fragment or link

**Comment by jxchen-us** [comment]
Sravan, is this still happening now that #37 is fixed?

**Comment by sravanr** [comment]
Wohoo... Now I see 2 warning messages.

Skipped record: () from /Test/mlcp-export-xmlquery-filter/fruit3.xml in file:MLDHOME/Forests/mlcp-f15a/00000000/TreeData, reason: fragment or linkSkipped record: () from /Test/mlcp-export-xmlquery-filter/naked/example.xml in file:MLDHOME/Forests/mlcp-f15a/00000000/TreeData, reason: fragment or link
