### ISSUE TITLE
MLCP documentation typo

### ISSUE THREAD

**Issue by sanjuthomas** [marklogic/marklogic-contentpump#42]
Open https://docs.marklogic.com/guide/mlcp.pdf

Go to page number 72

Look at the example command given - 

`mlcp.sh copy -mode local -host srchost -port 8000 \
 -username user -password password \
 -input_file_path /space/mlcp/txform/data \
 -transform_module /example/mlcp-transform.sjs \
 -transform_function transform \
 -transform_param "my-value"`

Should this be '**import**' instead of '**copy**' ?

**Comment by yunzvanessa** [comment]
Just verified that this typo has been fixed. Thanks.
