### ISSUE TITLE
Document how to use mlcp-mapr bundle

### ISSUE THREAD

**Issue by mattsunsjf** [marklogic/marklogic-contentpump#44]
Should let users know that mlcp-mapr bundle has a dependency on maprfs java library and we don't include this library in our deliverable. Give instructions on how to resolve depencencies.

From MapR documentation, I find their maven repo is:
http://repository.mapr.com/maven/

The artifact mlcp depends on is
``` xml
<groupId>com.mapr</groupId>
<artifactId>mapr-release</artifactId>
<version>5.1.0-mapr</version>
```

**Comment by mattsunsjf** [comment]
The direct link to the jar is here: 
http://repository.mapr.com/nexus/content/groups/mapr-public/com/mapr/hadoop/maprfs/5.1.0-mapr/
File name: maprfs-5.1.0-mapr.jar

**Comment by mattsunsjf** [comment]
The only dependency the users need to resolve is the maprfs jar. So we want to document the steps to download the jar and put into mlcp/lib.

**Comment by kcoleman-marklogic** [comment]
Matt, please see the related bugtrack issue for the new content to be reviewed. You can either close the bug (if you're satisfied) or reassign it to me (if corrections are needed).

**Comment by mattsunsjf** [comment]
The file name is `maprfs-5.1.0-mapr.jar`, so the version of this jar is actually `5.1.0-mapr`.
Chapter `Using mlcp With MapR`, i think we don't need to have the maven dependency thing. I'm afraid it's confusing.

**Comment by kcoleman-marklogic** [comment]
Are you certain "-mapr" is part of the version? I looked around the directory tree on the download site and see no evidence that there is every any other suffix. I think that's just their naming convention: thing-version-mapr. 

Saying it is part of the version implies it is part of the pathname that varies.

**Comment by kcoleman-marklogic** [comment]
Thanks, Matt. Docs updated as per your recommendations and our discussion.
