### ISSUE TITLE
MarkLogic Hadoop connector examples missing in 2.1.6 

### ISSUE THREAD

**Issue by maachou** [marklogic/marklogic-contentpump#51]
Open MarkLogic doc [Hadoop HelloWorld example](http://docs.marklogic.com/guide/mapreduce/quickstart#id_77461) 
In step 3 we mention $CONNECTOR_HOME/lib/marklogic-mapreduce-examples-version.jar
This jar is not found in the 2.1.6 package.
<img width="684" alt="connector_libs" src="https://cloud.githubusercontent.com/assets/879083/20433101/798d431e-ada2-11e6-87fe-265fd3a084b7.png">
  
<img width="1422" alt="doc_section" src="https://cloud.githubusercontent.com/assets/879083/20433128/93cfa488-ada2-11e6-98b4-56d854d9fad7.png">

**Comment by kcoleman-marklogic** [comment]
Matt, do we no longer ship the Hadoop Connector examples jar in the packaged distribution, or is this a packaging bug?

If we intentionally don't ship it any longer, what is the expectation for users? Are they supposed to clone the project and build the examples themselves? Please reassign this to me to so I do something with the documentation if we're no longer going to bundle the examples.

**Comment by kcoleman-marklogic** [comment]
@mattsunsjf P.S. Please also include instructions for building the examples from the project clone if you reassign this to me. It's not covered by the project README, AFAICT.

**Comment by mattsunsjf** [comment]
This is a packaging problem.

**Comment by kcoleman-marklogic** [comment]
Sravan, I think you might be in a better to verify this than I am, so I'm reassigning this to you.
