### ISSUE TITLE
MLCP User Guide Typo/Error

### ISSUE THREAD

**Issue by sanjuthomas** [marklogic/marklogic-contentpump#55]
Look at the MLCP user guide page number 45

` cat delim.opt
-input_file_type
delimited_text
-delimiter
"tab"`

It says a delimiter can be **"tab"**

now look at the page number 78

**it says -delimiter data type is a character.**

**Comment by mattsunsjf** [comment]
I think the doc means an escaped character "tab". But still, we should avoid the confusion.

**Comment by jmakeig** [comment]
In bash you’d use `$'\t'` to get a literal tab character (or Ctl+v, Tab key if you’re typing interactively). I don’t know how Windows handles this in `.bat` scripts.

**Comment by kcoleman-marklogic** [comment]
I do not believe there is a bug here. The documentation introducing that example explicitly says the value should be a tab character. Specifically, it says the following:

In the example options file below, **the string literal after -delimiter should contain a tab character**.

Not \t or any other escaped hocus pocus. Literally, it must be a tab character. I have no magical way to represent that invisible character other than with words.
