### ISSUE TITLE
copy_collections option not working in mlcp IMPORT

### ISSUE THREAD

**Issue by puramm** [marklogic/marklogic-contentpump#56]
### **copy_collections option is not working in mlcp IMPORT**

Steps to reproduce:

1. Exported data along with the collections using mlcp EXPORT command.

_mlcp EXPORT -host $ML_INPUT_HOST -username $ML_INPUT_USER -password $ML_INPUT_PASSWORD -port $ML_INPUT_PORT -database $ML_SOURCE_CONTENT_DB -output_file_path ./data **-copy_collections true**_

2. Imported the data into marklogic from the same /data directory where the document are exported

_mlcp IMPORT -host $ML_OUTPUT_HOST -username $ML_OUTPUT_USER -password $ML_OUTPUT_PASSWORD -port $ML_OUTPUT_PORT -database $ML_DESTINY_CONTENT_DB -input_file_path ./data **-copy_collections true** -document_type xml -output_uri_replace "/C:/mlcp-8.0-4/mlcp-8.0-4/bin/data,''"_

3. On verifying, documents are Imported but the collections are not  propagated.

**Is there any issue with **copy_collections true** while mlcp IMPORT?**

**Comment by mattsunsjf** [comment]
Hi Puramm,

While you export, you didn't specify `-output_type`, which by default is `document`. Meta data including collection information are not exported if output_type is document. Thus you won't see collections after you import them back to database.

Use `-output_type archive` in export command, and `-input_file_type archive` in import command to preserve meta data.

**Comment by puramm** [comment]
Thank you @mattsunsjf .
now its working.
