### ISSUE TITLE
MLCP Export - Document Selector Issue

### ISSUE THREAD

**Issue by SravyaKesiraju** [marklogic/marklogic-contentpump#59]
While exporting when I was using -document_selector  with date range conditions >= and <= ,I am not able to export the data 

Sample XML 

``` xml
<root><loadTime>2017-05-03T02:08:00.796029-05:00</loadTime><name>John</name></root>
<root><loadTime>2017-05-03T07:08:00.796029-05:00</loadTime><name>Ram</name></root>
<root><loadTime>2017-05-05T07:08:00.796029-05:00</loadTime><name>Sam</name></root>
```
Consider the above XML are in the marklogic
When I tried to export using -document_selector 
with condition as 

``` xquery
/root[loadTime >= xs:dateTime("2017-05-03T02:08:00.796029-05:00") and loadTime <= xs:dateTime("2017-05-04T07:08:00.796029-05:00")
```

then in the output I got Zero records, even though we have data for it.

But when I gave > and < it is working.
``` xquery
/root[loadTime > xs:dateTime("2017-05-03T03:08:00.796029-05:00") and loadTime < xs:dateTime("2017-05-04T08:08:00.796029-05:00")
```

So can you please suggest us what is the issue when we use >= and <=?

**Comment by mattsunsjf** [comment]
Not sure if this is a copy/paste issue, but you missed a square bracket `]` at the end.
Your example works for me, I was able to export documents.

Maybe you want to try options file. the `>` used in bash might be a problem.

**Comment by jxchen-us** [comment]
Please provide a reproducible test case, including the sample data, mlcp command and mlcp output log.

**Comment by jxchen-us** [comment]
Please re-open when the requested information is provided.  

Thanks.
