### ISSUE TITLE
MLCP does not set non-zero exit status upon error

### ISSUE THREAD

**Issue by hanshuebner** [marklogic/marklogic-contentpump#62]
MLCP does not return failure status by the way of its exit code.  That makes it rather hard to integrate it into automated processes in a robust fashion.

Example:

```
imogas 1005_% mlcp import -host localhost -port 8000 -input_file_path foo
17/06/20 00:25:54 INFO contentpump.LocalJobRunner: Content type is set to MIXED.  The format of the  inserted documents will be determined by the MIME  type specification configured on MarkLogic Server.
17/06/20 00:25:54 INFO contentpump.ContentPump: Job name: local_1494554887_1
17/06/20 00:25:54 ERROR contentpump.LocalJobRunner: Error checking output specification:
17/06/20 00:25:54 ERROR contentpump.LocalJobRunner: No input files found with the specified input path file:/home/hans/Development/configuration-service/foo and input file pattern .*
imogas 1006_% echo $?
0
```
The expected exit status would have been non-zero.  At present, non-exit error status is generated by MLCP only for usage errors, not for execution errors.

**Comment by grtjn** [comment]
See also this mail thread for more details: http://marklogic.markmail.org/thread/7ir4xta27uln4xh7#query:+page:1+mid:7ir4xta27uln4xh7+state:results

**Comment by grtjn** [comment]
In addition to Java not returning a proper exit status, I suspect that the mlcp.bat and mlcp.sh scripts are not propagating the exit status either.

**Comment by mattsunsjf** [comment]
@jxchen-us Did you have a similar bug?

**Comment by jxchen-us** [comment]
Matt, see bug https://bugtrack.marklogic.com/35847.

**Comment by grtjn** [comment]
I saw that bugtrack ticket too. It looks related but not the same to me..
