### ISSUE TITLE
Obfuscate password in mlcp log output

### ISSUE THREAD

**Issue by peetkes** [marklogic/marklogic-contentpump#82]
Is there a way to hide/obfuscate the password in the mlcp log output?
When you run an MLCP command, the password is visible in the log output
see below:
``
com.marklogic.contentpump.ContentPump IMPORT -port 8040 -input_file_path data/models -transform_namespace http://acne.com/datahub/duplicate-check -transform_module /ext/transforms/duplicate-check.xqy -input_file_type documents -output_permissions acne-datahub-configuration-role,read,rest-reader,read,rest-writer,update -transform_param model -
document_type xml -output_uri_replace .*data/,'/' -output_collections models, configuration -database acne-datahub-content -host localhost -username admin -password admin
 ``

**Comment by mattsunsjf** [comment]
Not out of box. Though mlcp does hide password in audit log when the user is doing export or copy. I think it won't be hard to do the same thing for console output.

Which version is it? @peetkes

**Comment by yunzvanessa** [comment]
This issue is fixed in marklogic 9.0-11 release (scheduled for this month) and 10.0-3 release (scheduled next month). Thanks for reporting!

Vanessa
